# Generated by Django 3.0.3 on 2020-03-09 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_thumbs_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='user_thumbs_up',
            field=models.ManyToManyField(related_name='thumbs', to=settings.AUTH_USER_MODEL),
        ),
    ]
