# Generated by Django 3.0.3 on 2020-03-24 17:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200315_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='post_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
    ]
