# Generated by Django 3.0.3 on 2020-03-24 22:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPicture',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='post_pics'),
        ),
    ]
