# Generated by Django 3.0.3 on 2020-03-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200331_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpicture',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_pictures', to='blog.Post'),
        ),
    ]
