# Generated by Django 3.0.3 on 2020-03-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_postpicture_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
        migrations.DeleteModel(
            name='PostPicture',
        ),
    ]
