# Generated by Django 3.0.3 on 2020-04-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
